version: '2.1'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dev
      DB_USER: root
      USER_PASSWD: dev
    ports:
      - '3307:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./config/db/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  redis:
    tty: true
    image: redis:alpine
    ports:
      - '6378:6379'
    stdin_open: true


  ssj-server:
    build: .
    ports:
      - '8888:8089'
    environment:
      ACTIVE_PROFILE: integ
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: dev
    depends_on:
      - mysql
      - redis


  nginx:
    image: nginx
    ports:
      - '9000:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
